---
title: "report"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(jsonlite)
library(tidyverse)
library(knitr)
pop<-read_csv2('../Wrangle/popolazioneresidenteperetasessoestatocivileanno2013.csv')
```

## Le strutture

Scarichiamo strutture dagli opendata della regione toscana

```{r download}

resp<-fromJSON("http://servizi.toscana.it/RT/mappe/strutturericettiveXall.json?_ga=2.17440825.1225592402.1525851067-977727594.1525851067")
strutture<-resp$strutturericettiveXall$SelXall
```

il numero di struttura per provincia

```{r strutture}
nstrutture<-strutture%>%count(provincia)%>% rename("numero strutture"=n)
kable(nstrutture)
```

la distribuzione delle strutture per tipologia e stelle

```{r plot }
ggplot(data=strutture)+geom_bar(mapping=aes(x=tipologia,fill=stelle))+coord_flip()
```

## La popolazione

importiamo la polazione per il 2013. la tabella per provincia

```{r pop}

npop <- pop %>% group_by(Provincia) %>% summarise(npop=sum(PopolazioneTotale)) %>%rename(provincia=Provincia,"popolazione 2013"=npop) 
kable(npop)
```


il numero di strutture e la popolazione

```{r ris}
kable(nstrutture%>%inner_join(npop,by=c("provincia"="provincia")))
```

